name: Build & Release

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  buildFlutter:
    name: Build (APK and AAB)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Set up Secrets
        run: |
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
          echo "STORE_FILE=${{ secrets.STORE_FILE }}" >> $GITHUB_ENV
          echo "STORE_PASSWORD=${{ secrets.STORE_PASSWORD }}" >> $GITHUB_ENV

      - name: Create Keystore File
        run: echo "${{ secrets.KEYSTORE_FILE_CONTENT }}" | base64 --decode > islamxplorer_flutter/android/app/upload-keystore.jks

      - name: Echo Keystore File Contents
        run: cat islamxplorer_flutter/android/app/upload-keystore.jks
        
      - name: Debug STORE_FILE
        run: echo "STORE_FILE=$(pwd)/islamxplorer_flutter/android/app/upload-keystore.jks"

      - name: Build APK and AAB
        run: |
          cd islamxplorer_flutter  # Change to the Flutter project directory
          flutter build apk --release --split-per-abi
          flutter build appbundle --release

      - name: Push to Releases (GitHub Releases)
        uses: ncipollo/release-action@v1
        with:
          artifacts: "islamxplorer_flutter/build/app/outputs/apk/release/*, islamxplorer_flutter/build/app/outputs/bundle/release/*"
          tag: v2.0.${{ github.run_number }}
          token: ${{ secrets.CLI_TOKEN }}

      - name: Upload app bundle
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: islamxplorer_flutter/build/app/outputs/bundle/release/app-release.aab
  releaseFlutter:
    name: Release (PlayStore)
    needs: [buildFlutter]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Get appbundle from artifacts
        uses: actions/download-artifact@v2
        with:
          name: appbundle
      - name: Upload to Play Store (Production)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON }} 
          packageName: com.islamxplorer.islamxplorer_flutter                       
          releaseFiles: app-release.aab
          track: production
