name: Build & Release

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Set up Secrets
        run: |
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
          echo "STORE_FILE=${{ secrets.STORE_FILE }}" >> $GITHUB_ENV
          echo "STORE_PASSWORD=${{ secrets.STORE_PASSWORD }}" >> $GITHUB_ENV

      - name: Create Keystore File
        run: echo "${{ secrets.KEYSTORE_FILE_CONTENT }}" | base64 --decode > islamxplorer_flutter/android/app/upload-keystore.jks

      - name: Debug STORE_FILE
        run: echo "STORE_FILE=$(pwd)/islamxplorer_flutter/android/app/upload-keystore.jks"

      - name: Build APK and IPA
        run: |
          cd islamxplorer_flutter  # Change to the Flutter project directory
          flutter build apk --release --split-per-abi
          flutter build ipa --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "islamxplorer_flutter/build/app/outputs/apk/release/*,islamxplorer_flutter/build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}

